---
- name: Работа со службами Windows
  hosts: windows
  tasks:
    - name: Узнать статус службы BITS
      win_service:
        name: BITS
        state: started
      register: service_info
      
    - name: Показать статус
      debug:
        var: service_info
        
    - name: Остановить службу (если запущена)
      win_service:
        name: Spooler
        state: stopped
